BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "person" (
	"id"	INTEGER NOT NULL,
	"name"	NVARCHAR(80) NOT NULL,
	"age"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "cat" (
	"id"	INTEGER NOT NULL,
	"name"	NVCHAR(80) NOT NULL,
	"owner_id"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("owner_id") REFERENCES "person"("id") ON DELETE CASCADE
);
INSERT INTO "person" VALUES (1,'Irina',35);
INSERT INTO "cat" VALUES (1,'Chat',1);
INSERT INTO "cat" VALUES (2,'boule de neige',1);
COMMIT;